# Project: TSP_Genetic
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = main.o LinkedListInts.o LinkInt.o SetInts.o $(RES)
LINKOBJ  = main.o LinkedListInts.o LinkInt.o SetInts.o $(RES)
LIBS =  -L"C:/Dev-Cpp/lib" -L"C:/Dev-Cpp/include/Pre-built/lib"  
INCS =  -I"C:/Dev-Cpp/include"  -I"C:/Dev-Cpp/include/pthreads"  -I"C:/Dev-Cpp/include/Pre-built/include" 
CXXINCS =  -I"C:/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Dev-Cpp/include/c++/3.4.2/backward"  -I"C:/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"C:/Dev-Cpp/include/c++/3.4.2"  -I"C:/Dev-Cpp/include"  -I"C:/Dev-Cpp/include/Pre-built/include" 
BIN  = TSP_Genetic.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before TSP_Genetic.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "TSP_Genetic.exe" $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

LinkedListInts.o: LinkedListInts.cpp
	$(CPP) -c LinkedListInts.cpp -o LinkedListInts.o $(CXXFLAGS)

LinkInt.o: LinkInt.cpp
	$(CPP) -c LinkInt.cpp -o LinkInt.o $(CXXFLAGS)

SetInts.o: SetInts.cpp
	$(CPP) -c SetInts.cpp -o SetInts.o $(CXXFLAGS)
